common: &common
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  username: root
  socket: /tmp/mysql.sock

development:
  <<: *common
  database: atlist_app_development

test:
  <<: *common
  database: atlist_app_test